qlab/apps/base/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views


app_name = "base"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("members/", views.members, name="members"),
    path("members/<int:year>/", views.members, name="members"),
    path("partners/", views.partners, name="partners"),
    path("about/tour/", views.about_tour, name="about_tour"),
    path("about/music/", views.about_music, name="about_music"),
    path("about/resources/", views.about_resources, name="about_resources"),
    path("donate/", views.donate, name="donate"),
]

qlab/apps/projects/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views


app_name = "projects"

urlpatterns = [
    path("", views.project_list, name="project_list"),
    path("<int:year>/", views.project_list, name="project_list"),
    path("detail/<int:project_id>/", views.project_detail, name="project_detail"),
    path("edit/<int:project_id>/", views.project_edit, name="project_edit"),
    path("post/add/<int:project_id>/", views.post_add, name="post_add"),
    path("post/edit/<int:project_id>/<int:post_id>/", views.post_edit, name="post_edit"),
    path("photo/add/<int:project_id>/", views.photo_add, name="photo_add"),
    path("file/add/<int:project_id>/", views.file_add, name="file_add"),
]

qlab/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include('qlab.apps.base.urls', namespace='base')),
    path('projects/', include('qlab.apps.projects.urls', namespace='projects')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

qlab/apps/base/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    id = models.AutoField(primary_key=True)

    graduation_year = models.IntegerField(blank=True, null=True)

    is_alumni = models.BooleanField(default=False)
    is_lab_student = models.BooleanField(default=False)
    
    display_first_last = models.BooleanField(default=False, verbose_name="Display first and last name")

    picture = models.FileField(upload_to="student_photos/", blank=True, null=True, help_text="Deprecated. Select college instead.")
    college = models.ForeignKey("College", on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        ordering = ("last_name", "first_name")

    def get_social_auth(self):
        return self.social_auth.get(provider="ion")
    
    @property
    def display_name(self):
        return f"{self.first_name} {self.last_name}" if self.display_first_last else self.first_name

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class ResearchPartner(models.Model):
    id = models.AutoField(primary_key=True)

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)

    picture = models.FileField(upload_to="partner_photos/")


    def __str__(self):
        return self.name


class CarouselPhoto(models.Model):
    id = models.AutoField(primary_key=True)

    time_created = models.DateTimeField(auto_now_add=True)

    image = models.FileField(upload_to="carousel_photos/")
    caption = models.CharField(max_length=200)


    class Meta:
        ordering = ("-time_created",)


    def __str__(self):
        return f"Photo {self.id} ({self.caption})"


class Resource(models.Model):
    id = models.AutoField(primary_key=True)

    CATEGORIES = (
        ("learn", "Learn Quantum"),
        ("articles", "Articles"),
        ("comps", "Competitions + Games"),
        ("opps", "Opportunities"),
    )
    category = models.CharField(max_length=8, choices=CATEGORIES)

    time_created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    link = models.CharField(max_length=500)


    class Meta:
        ordering = ("-time_created",)


    def __str__(self):
        return self.name


class Song(models.Model):
    id = models.AutoField(primary_key=True)
    
    title = models.CharField(max_length=50)
    artist_name = models.CharField(max_length=50)
    link = models.URLField()


    def __str__(self):
        return f"{self.title} by {self.artist_name}"


class College(models.Model):
    name = models.CharField(max_length=200)
    logo = models.FileField(upload_to="college_logos/")

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

qlab/apps/projects/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Project(models.Model):
    id = models.AutoField(primary_key=True)

    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(get_user_model())
    description = models.TextField(max_length=5000)
    last_updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    poster_url = models.URLField(blank=True)
    presentation_url = models.URLField(blank=True)
    video_url = models.URLField(blank=True)
    paper_url = models.URLField(blank=True)

    def __str__(self):
        return self.title

    def author_string(self):
        return ", ".join([u.display_name for u in self.authors.all()])

    def can_edit_or_post(self, user):
        return user in self.authors.all() or user.is_superuser

    def get_last_post(self):
        return self.post_set.all()[0]

    def has_info_urls(self):
        return self.poster_url or self.presentation_url or self.video_url or self.paper_url

    def info_urls(self):
        return {
            "Poster": self.poster_url,
            "Presentation": self.presentation_url,
            "Paper": self.paper_url,
            "Video": self.video_url,
        }


class Post(models.Model):
    id = models.AutoField(primary_key=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    last_updated = models.DateTimeField(auto_now=True)

    content = models.TextField()


    class Meta:
        ordering = ("-last_updated",)


    def __str__(self):
        return f"Post on {self.last_updated} for {self.project} by {self.author}"


class Photo(models.Model):
    id = models.AutoField(primary_key=True)

    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    time_uploaded = models.DateTimeField(auto_now_add=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.FileField(upload_to="project_photos/")


    def __str__(self):
        return f"Photo for {self.project.title} (ID: {self.id})"

    def can_edit(self, user):
        return self.project.can_edit_or_post(user)
    

class File(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    time_uploaded = models.DateTimeField(auto_now_add=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file = models.FileField(upload_to="project_files/")

    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)


    def __str__(self):
        return f"File for {self.project.title} (ID: {self.id})"

    def can_edit(self, user):
        return self.project.can_edit_or_post(user)

qlab/apps/projects/forms.py
from django import forms

from .models import Post, Project


class ProjectEditForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "title",
            "description",
            "active",
        ]
        labels = {
            "title": "Project Title",
            "description": "Project Description",
            "active": "Active Project?"
        }


class PostForm(forms.Form):
    content = forms.CharField(max_length=5000, widget=forms.Textarea)


class PhotoForm(forms.Form):
    image = forms.FileField(allow_empty_file=False, required=True)


class FileForm(forms.Form):
    title = forms.CharField(max_length=100, required=True)
    description = forms.CharField(widget=forms.Textarea, required=False)
    file = forms.FileField(allow_empty_file=False, required=True)

qlab/apps/base/views.py
from django.shortcuts import render

from .models import CarouselPhoto, ResearchPartner, Resource, Song, User
from ..projects.models import Project


def index(request):
    context = {"projects": Project.objects.all().order_by("-last_updated")[:7]}
    return render(request, "base/index.html", context=context)


def login(request):
    return render(request, "base/login.html")


def members(request, year=None):
    context = {
        "years": User.objects.filter(is_alumni=True).exclude(graduation_year__isnull=True).values_list("graduation_year", flat=True).distinct().order_by("graduation_year"),
        "year": year,
    }

    if year:
        context["students"] = [(u, u.project_set.all()) for u in User.objects.filter(graduation_year=year, is_alumni=True).order_by("first_name")]
    else:
        context["students"] = [(u, u.project_set.all()) for u in User.objects.filter(is_lab_student=True).order_by("graduation_year", "first_name")]

    return render(request, "base/members.html", context=context)


def partners(request):
    context = {"partners": ResearchPartner.objects.all()}
    return render(request, "base/partners.html", context=context)


def about_tour(request):
    context = {"photos": CarouselPhoto.objects.all()}
    return render(request, "base/about/tour.html", context=context)


def about_music(request):
    context = {"songs": Song.objects.all()}
    return render(request, "base/about/music.html", context=context)


def about_resources(request):
    context = {
        "learn": Resource.objects.filter(category="learn"),
        "articles": Resource.objects.filter(category="articles"),
        "comps": Resource.objects.filter(category="comps"),
        "opps": Resource.objects.filter(category="opps"),
    }
    return render(request, "base/about/resources.html", context=context)


def donate(request):
    return render(request, "base/donate.html")

qlab/apps/projects/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import PhotoForm, PostForm, ProjectEditForm, FileForm
from .models import Photo, Post, Project, File
from ..base.models import User


def project_list(request, year=None):
    context = {
        "years": User.objects.filter(is_alumni=True).exclude(graduation_year__isnull=True).values_list("graduation_year", flat=True).distinct().order_by("graduation_year"),
        "year": year,
    }
    if year:
        context["projects"] = Project.objects.filter(authors__graduation_year=year, authors__is_alumni=True).distinct().order_by("-active", "-last_updated")
    else:
        context["projects"] = Project.objects.filter(authors__is_lab_student=True).distinct().order_by("-active", "-last_updated")
    return render(request, "projects/list.html", context=context)


def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    context = {
        "editor": project.can_edit_or_post(request.user),
        "project": project,
        "posts": project.post_set.all(),
        "photos": project.photo_set.all(),
        "files": project.file_set.all(),
    }

    return render(request, "projects/detail.html", context=context)


@login_required
def project_edit(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if project.can_edit_or_post(request.user):
        form = ProjectEditForm(instance=project)

        if request.method == "POST":
            form = ProjectEditForm(request.POST, instance=project)
            if form.is_valid():
                form.save()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/edit.html", context={"form": form})
    else:
        raise PermissionDenied


@login_required
def post_add(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if project.can_edit_or_post(request.user):
        form = PostForm()

        if request.method == "POST":
            form = PostForm(request.POST)
            if form.is_valid():
                post = Post.objects.create(
                    project=project,
                    author=request.user,
                    content=form.cleaned_data["content"],
                )
                project.save()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/post.html", context={"action": "Add", "project": project, "form": form})
    else:
        raise PermissionDenied


@login_required
def post_edit(request, project_id, post_id):
    project = get_object_or_404(Project, id=project_id)
    post = get_object_or_404(Post.objects.filter(project=project), id=post_id)

    if project.can_edit_or_post(request.user):
        form = PostForm(initial={"content": post.content})

        if request.method == "POST":
            if "button-save" in request.POST:
                form = PostForm(request.POST)
                if form.is_valid():
                    post.content = form.cleaned_data["content"]
                    post.save()
                    project.save()
                    return redirect(reverse("projects:project_detail", args=[project.id]))
            elif "button-delete" in request.POST:
                post.delete()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/post.html", context={"action": "Edit", "project": project, "form": form})
    else:
        raise PermissionDenied


@login_required
def photo_add(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if project.can_edit_or_post(request.user):
        form = PhotoForm()

        if request.method == "POST":
            form = PhotoForm(request.POST, request.FILES)
            if form.is_valid():
                photo = Photo.objects.create(
                    project=project,
                    owner=request.user,
                    image=form.cleaned_data["image"],
                )
                project.save()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/photo.html", context={"project": project, "form": form})
    else:
        raise PermissionDenied


@login_required
def file_add(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if project.can_edit_or_post(request.user):
        form = FileForm()

        if request.method == "POST":
            form = FileForm(request.POST, request.FILES)
            if form.is_valid():
                file = File.objects.create(
                    project=project,
                    owner=request.user,
                    title=form.cleaned_data["title"],
                    description=form.cleaned_data["description"],
                    file=form.cleaned_data["file"],
                )
                project.save()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/file.html", context={"project": project, "form": form})
    else:
        raise PermissionDenied

qlab/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Q Lab</title>
        <meta name="author" content="Lauren Delwiche">
        <link rel="icon" href="{% static 'img/logos/short.png' %}">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/fdf6dd33bb.js" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'css/nav.css' %}">
        <link rel="stylesheet" href="{% static 'css/footer.css' %}">

        <style>
            .credit {
                position: absolute;
                bottom: 0;
                font-size: 13px;
            }
        </style>

        {% block head %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}

        <footer>
            <div class="row">
                <div class="col-lg-2 col-md-1"></div>
                <div class="col-lg-4 col-md-5 center-text">
                    <img class="foot-img" src="{% static 'img/logos/short-moose.png' %}" />
                </div>
                <div class="col-lg-4 col-md-5 left-text">
                    <h3>Contact Us!</h3>
                    <br>
                    <p>
                        Mr. Mark Hannum, Lab Director
                        <a class="icon" target="_blank" href="mailto:mshannum@fcps.edu"><i class="fa-solid fa-envelope"></i></a>
                        <a class="icon" target="_blank" href="https://twitter.com/MarketyMark/"><i class="fa-brands fa-twitter"></i></a>
                    </p>
                    <p class="credit">
                        Built by <a class="icon" target="_blank" href="https://github.com/Laur04">@Laur04</a>
                    </p>
                </div>
                <div class="col-lg-2 col-md-1"></div>
            </div>
        </footer>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

qlab/templates/base_with_head.html
{% extends "base.html" %}

{% load static %}

{% block body %}
    <div class="brand-head">
        <a href="{% url 'base:index' %}">
            <img class="brand-img" src="{% static 'img/logos/long.png' %}" />
        </a>
    </div>
    {% include "nav.html" %}

    <main>
        {% block main %}{% endblock %}
    </main>
{% endblock %}

qlab/templates/nav.html
{% load static %}

<nav>
    <div class="navbar navbar-expand-md bar-background">
        <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div  class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav nav-fill w-100 me-auto">
                <li class="nav-item"><a class="nav-link bar-link" href="{% url 'base:index' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link bar-link" href="{% url 'base:members' %}">Members</a></li>
                <li class="nav-item"><a class="nav-link bar-link" href="{% url 'projects:project_list' %}">Projects</a></li>
                <li class="nav-item"><a class="nav-link bar-link" href="{% url 'base:partners' %}">Partners</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link bar-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About</a>
                    <div class="dropdown-menu bar-drop" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item bar-drop-item" href="{% url 'base:about_tour' %}">Lab Tour</a>
                      <a class="dropdown-item bar-drop-item" href="{% url 'base:about_music' %}">Playlists</a>
                      <a class="dropdown-item bar-drop-item" href="{% url 'base:about_resources' %}">Resources</a>
                    </div>
                  </li>
                {# <li class="nav-item"><a class="nav-link bar-link" href="{% url 'base:donate' %}">Donate</a></li> #}
            </ul>
        </div>
    </div>
</nav>