qlab/apps/base/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views


app_name = "base"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("members/", views.members, name="members"),
    path("members/<int:year>/", views.members, name="members"),
    path("partners/", views.partners, name="partners"),
    path("about/tour/", views.about_tour, name="about_tour"),
    path("about/music/", views.about_music, name="about_music"),
    path("about/resources/", views.about_resources, name="about_resources"),
    path("donate/", views.donate, name="donate"),
]

qlab/apps/projects/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views


app_name = "projects"

urlpatterns = [
    path("", views.project_list, name="project_list"),
    path("<int:year>/", views.project_list, name="project_list"),
    path("detail/<int:project_id>/", views.project_detail, name="project_detail"),
    path("edit/<int:project_id>/", views.project_edit, name="project_edit"),
    path("post/add/<int:project_id>/", views.post_add, name="post_add"),
    path("post/edit/<int:project_id>/<int:post_id>/", views.post_edit, name="post_edit"),
    path("photo/add/<int:project_id>/", views.photo_add, name="photo_add"),
    path("file/add/<int:project_id>/", views.file_add, name="file_add"),
]

qlab/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include('qlab.apps.base.urls', namespace='base')),
    path('projects/', include('qlab.apps.projects.urls', namespace='projects')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

qlab/apps/base/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    id = models.AutoField(primary_key=True)

    graduation_year = models.IntegerField(blank=True, null=True)

    is_alumni = models.BooleanField(default=False)
    is_lab_student = models.BooleanField(default=False)
    
    display_first_last = models.BooleanField(default=False, verbose_name="Display first and last name")

    picture = models.FileField(upload_to="student_photos/", blank=True, null=True, help_text="Deprecated. Select college instead.")
    college = models.ForeignKey("College", on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        ordering = ("last_name", "first_name")

    def get_social_auth(self):
        return self.social_auth.get(provider="ion")
    
    @property
    def display_name(self):
        return f"{self.first_name} {self.last_name}" if self.display_first_last else self.first_name

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class ResearchPartner(models.Model):
    id = models.AutoField(primary_key=True)

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)

    picture = models.FileField(upload_to="partner_photos/")


    def __str__(self):
        return self.name


class CarouselPhoto(models.Model):
    id = models.AutoField(primary_key=True)

    time_created = models.DateTimeField(auto_now_add=True)

    image = models.FileField(upload_to="carousel_photos/")
    caption = models.CharField(max_length=200)


    class Meta:
        ordering = ("-time_created",)


    def __str__(self):
        return f"Photo {self.id} ({self.caption})"


class Resource(models.Model):
    id = models.AutoField(primary_key=True)

    CATEGORIES = (
        ("learn", "Learn Quantum"),
        ("articles", "Articles"),
        ("comps", "Competitions + Games"),
        ("opps", "Opportunities"),
    )
    category = models.CharField(max_length=8, choices=CATEGORIES)

    time_created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    link = models.CharField(max_length=500)


    class Meta:
        ordering = ("-time_created",)


    def __str__(self):
        return self.name


class Song(models.Model):
    id = models.AutoField(primary_key=True)
    
    title = models.CharField(max_length=50)
    artist_name = models.CharField(max_length=50)
    link = models.URLField()


    def __str__(self):
        return f"{self.title} by {self.artist_name}"


class College(models.Model):
    name = models.CharField(max_length=200)
    logo = models.FileField(upload_to="college_logos/")

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

qlab/apps/projects/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Project(models.Model):
    id = models.AutoField(primary_key=True)

    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(get_user_model())
    description = models.TextField(max_length=5000)
    last_updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    poster_url = models.URLField(blank=True)
    presentation_url = models.URLField(blank=True)
    video_url = models.URLField(blank=True)
    paper_url = models.URLField(blank=True)

    def __str__(self):
        return self.title

    def author_string(self):
        return ", ".join([u.display_name for u in self.authors.all()])

    def can_edit_or_post(self, user):
        return user in self.authors.all() or user.is_superuser

    def get_last_post(self):
        return self.post_set.all()[0]

    def has_info_urls(self):
        return self.poster_url or self.presentation_url or self.video_url or self.paper_url

    def info_urls(self):
        return {
            "Poster": self.poster_url,
            "Presentation": self.presentation_url,
            "Paper": self.paper_url,
            "Video": self.video_url,
        }


class Post(models.Model):
    id = models.AutoField(primary_key=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    last_updated = models.DateTimeField(auto_now=True)

    content = models.TextField()


    class Meta:
        ordering = ("-last_updated",)


    def __str__(self):
        return f"Post on {self.last_updated} for {self.project} by {self.author}"


class Photo(models.Model):
    id = models.AutoField(primary_key=True)

    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    time_uploaded = models.DateTimeField(auto_now_add=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.FileField(upload_to="project_photos/")


    def __str__(self):
        return f"Photo for {self.project.title} (ID: {self.id})"

    def can_edit(self, user):
        return self.project.can_edit_or_post(user)
    

class File(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    time_uploaded = models.DateTimeField(auto_now_add=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file = models.FileField(upload_to="project_files/")

    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)


    def __str__(self):
        return f"File for {self.project.title} (ID: {self.id})"

    def can_edit(self, user):
        return self.project.can_edit_or_post(user)

qlab/apps/projects/forms.py
from django import forms

from .models import Post, Project


class ProjectEditForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "title",
            "description",
            "active",
        ]
        labels = {
            "title": "Project Title",
            "description": "Project Description",
            "active": "Active Project?"
        }


class PostForm(forms.Form):
    content = forms.CharField(max_length=5000, widget=forms.Textarea)


class PhotoForm(forms.Form):
    image = forms.FileField(allow_empty_file=False, required=True)


class FileForm(forms.Form):
    title = forms.CharField(max_length=100, required=True)
    description = forms.CharField(widget=forms.Textarea, required=False)
    file = forms.FileField(allow_empty_file=False, required=True)

qlab/apps/base/views.py
from django.shortcuts import render

from .models import CarouselPhoto, ResearchPartner, Resource, Song, User
from ..projects.models import Project


def index(request):
    context = {"projects": Project.objects.all().order_by("-last_updated")[:7]}
    return render(request, "base/index.html", context=context)


def login(request):
    return render(request, "base/login.html")


def members(request, year=None):
    context = {
        "years": User.objects.filter(is_alumni=True).exclude(graduation_year__isnull=True).values_list("graduation_year", flat=True).distinct().order_by("graduation_year"),
        "year": year,
    }

    if year:
        context["students"] = [(u, u.project_set.all()) for u in User.objects.filter(graduation_year=year, is_alumni=True).order_by("first_name")]
    else:
        context["students"] = [(u, u.project_set.all()) for u in User.objects.filter(is_lab_student=True).order_by("graduation_year", "first_name")]

    return render(request, "base/members.html", context=context)


def partners(request):
    context = {"partners": ResearchPartner.objects.all()}
    return render(request, "base/partners.html", context=context)


def about_tour(request):
    context = {"photos": CarouselPhoto.objects.all()}
    return render(request, "base/about/tour.html", context=context)


def about_music(request):
    context = {"songs": Song.objects.all()}
    return render(request, "base/about/music.html", context=context)


def about_resources(request):
    context = {
        "learn": Resource.objects.filter(category="learn"),
        "articles": Resource.objects.filter(category="articles"),
        "comps": Resource.objects.filter(category="comps"),
        "opps": Resource.objects.filter(category="opps"),
    }
    return render(request, "base/about/resources.html", context=context)


def donate(request):
    return render(request, "base/donate.html")

qlab/apps/projects/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import PhotoForm, PostForm, ProjectEditForm, FileForm
from .models import Photo, Post, Project, File
from ..base.models import User


def project_list(request, year=None):
    context = {
        "years": User.objects.filter(is_alumni=True).exclude(graduation_year__isnull=True).values_list("graduation_year", flat=True).distinct().order_by("graduation_year"),
        "year": year,
    }
    if year:
        context["projects"] = Project.objects.filter(authors__graduation_year=year, authors__is_alumni=True).distinct().order_by("-active", "-last_updated")
    else:
        context["projects"] = Project.objects.filter(authors__is_lab_student=True).distinct().order_by("-active", "-last_updated")
    return render(request, "projects/list.html", context=context)


def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    context = {
        "editor": project.can_edit_or_post(request.user),
        "project": project,
        "posts": project.post_set.all(),
        "photos": project.photo_set.all(),
        "files": project.file_set.all(),
    }

    return render(request, "projects/detail.html", context=context)


@login_required
def project_edit(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if project.can_edit_or_post(request.user):
        form = ProjectEditForm(instance=project)

        if request.method == "POST":
            form = ProjectEditForm(request.POST, instance=project)
            if form.is_valid():
                form.save()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/edit.html", context={"form": form})
    else:
        raise PermissionDenied


@login_required
def post_add(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if project.can_edit_or_post(request.user):
        form = PostForm()

        if request.method == "POST":
            form = PostForm(request.POST)
            if form.is_valid():
                post = Post.objects.create(
                    project=project,
                    author=request.user,
                    content=form.cleaned_data["content"],
                )
                project.save()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/post.html", context={"action": "Add", "project": project, "form": form})
    else:
        raise PermissionDenied


@login_required
def post_edit(request, project_id, post_id):
    project = get_object_or_404(Project, id=project_id)
    post = get_object_or_404(Post.objects.filter(project=project), id=post_id)

    if project.can_edit_or_post(request.user):
        form = PostForm(initial={"content": post.content})

        if request.method == "POST":
            if "button-save" in request.POST:
                form = PostForm(request.POST)
                if form.is_valid():
                    post.content = form.cleaned_data["content"]
                    post.save()
                    project.save()
                    return redirect(reverse("projects:project_detail", args=[project.id]))
            elif "button-delete" in request.POST:
                post.delete()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/post.html", context={"action": "Edit", "project": project, "form": form})
    else:
        raise PermissionDenied


@login_required
def photo_add(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if project.can_edit_or_post(request.user):
        form = PhotoForm()

        if request.method == "POST":
            form = PhotoForm(request.POST, request.FILES)
            if form.is_valid():
                photo = Photo.objects.create(
                    project=project,
                    owner=request.user,
                    image=form.cleaned_data["image"],
                )
                project.save()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/photo.html", context={"project": project, "form": form})
    else:
        raise PermissionDenied


@login_required
def file_add(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if project.can_edit_or_post(request.user):
        form = FileForm()

        if request.method == "POST":
            form = FileForm(request.POST, request.FILES)
            if form.is_valid():
                file = File.objects.create(
                    project=project,
                    owner=request.user,
                    title=form.cleaned_data["title"],
                    description=form.cleaned_data["description"],
                    file=form.cleaned_data["file"],
                )
                project.save()
                return redirect(reverse("projects:project_detail", args=[project.id]))
        
        return render(request, "projects/file.html", context={"project": project, "form": form})
    else:
        raise PermissionDenied

qlab/templates/projects/detail.html
{% extends "base_with_head.html" %}

{% load static %}
{% load markdown_extras %}

{% block head %}
<style>
    .box {
        padding: 5px;
        margin: 15px;
        height: 90% !important;
    }

    .admin-btn {
        font-size: 1rem;
        display: inline;
        padding: 10px;
    }

    .photo-gallery {
        height: 200px;
        padding: 5px;
    }
</style>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML-full"></script>
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [["$", "$"], ["\\\\(", "\\\\)"]],
            displayMath: [["$$", "$$"], ["\\[", "\\]"]],
            processEscapes: true
        },
        config: ["MMLorHTML.js"],
        jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
        extensions: ["MathMenu.js", "MathZoom.js"]
    });
</script>
{% endblock %}

{% block main %}
    <div>
        <h2 class="primary">{{ project.title | markdown | safe }}</h2>
        <h5 class="primary">By {{ project.author_string }}
            {% if editor %} <a class="q-btn admin-btn" href="{% url 'projects:project_edit' project.id %}">Edit Info</a>{% endif %}
        </h5>
        <br>
        <h6>{{ project.description | markdown | safe }}</h6>
        {% if project.has_info_urls %}
        <div class="row urls-row">
            {% for name, url in project.info_urls.items %}
                {% if url %}
                <div class="col">
                    <a href="{{ url }}" target="_blank">
                        {{ name }}
                        {% if name == "Video" %}
                        <span class="fcps-only">(FCPS only)</span>
                        {% endif %}
                    </a>
                </div>
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br><hr><br>
    <div>
        <h2 class="primary-light">Files and Resources{% if editor %} <a class="q-btn admin-btn" href="{% url 'projects:file_add' project.id %}">Add File</a>{% endif %}</h2>
        {% for file in files %}
            <div class="box card">
                <div class="card-body">
                    <h5>{{ file.title }} <a href="{{ file.file.url }}"><i class="fa-solid fa-download"></i></a></h5>
                    <p>{{ file.description }}</p>
                </div>
            </div>
        {% endfor %}
        {% if not files %}
            <br>
            <h6>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Files are coming soon!</h6>
        {% endif %}
    </div>
    <br><br>
    <div>
        <h2 class="primary-light">Photo Gallery{% if editor %} <a class="q-btn admin-btn" href="{% url 'projects:photo_add' project.id %}">Add Photo</a>{% endif %}</h2>
        <br>
        {% for photo in photos %}
            <img class="photo-gallery" src="{{ photo.image.url }}" />
        {% endfor %}
        {% if not photos %}
            <br>
            <h6>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Photos are coming soon!</h6>
        {% endif %}
    </div>
    <br><br>
    <div>
        <h2 class="primary-light">Updates{% if editor %} <a class="q-btn admin-btn" href="{% url 'projects:post_add' project.id %}">Add Post</a>{% endif %}</h2>
        {% for post in posts %}
            <div class="box card">
                <div class="card-body">
                        <h5>{{ post.last_updated.date }}{% if editor %} <a href="{% url 'projects:post_edit' project.id post.id %}"><i class="fa-solid fa-pen-to-square"></i></a>{% endif %}</h5>
                        <p>{{ post.content | markdown | safe}}</p>
                    <br>
                </div>
            </div>
        {% endfor %}
        {% if not posts %}
            <br>
            <h6>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No updates yet. Stay tuned!</h6>
        {% endif %}
    </div>
    <br>
{% endblock %}

qlab/templates/projects/edit.html
{% extends "base_with_head.html" %}

{% load static %}

{% block head %}
    <style>
        #id_title {
            width: 70%;
            border: solid 1px var(--blue);
        }
    </style>
{% endblock %}

{% block main %}
    <h1 class="primary"><strong>Edit Project Info</strong></h1>
    <br>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="row">
                <div class="col-md-2 col-sm-12">
                    <label>{{ field.label }}:</label>
                </div>
                <div class="col-md-10 col-sm-12">
                    <p>{{ field }}</p>
                </div>
            </div>
        {% endfor %}
        <input class="btn q-btn" type="submit" value="Save">
    </form>    
{% endblock %}

qlab/templates/projects/file.html
{% extends "base_with_head.html" %}

{% load static %}

{% block head %}
    <style>
        #id_title {
            width: 70%;
        }

        .height-holder {
            height: 25vh;
        }
    </style>
{% endblock %}

{% block main %}
    <h1 class="primary"><strong>Add File</strong></h1>
    <h5>Project: {{ project }}</h5>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn q-btn" type="submit" name="button-save" value="Save">
    </form>
    <div class="height-holder"></div>
{% endblock %}

qlab/templates/projects/list.html
{% extends "base_with_head.html" %}

{% load static %}
{% load markdown_extras %}

{% block head %}
<style>
    main > .row {
        row-gap: 20px;
    }
    
    .box {
        padding: 0;
        margin: 0;
        height: 98% !important;
        color: var(--black);
    }

    .box:hover {
        border: solid 8px var(--blue);
        color: var(--black);
    }

    .light-blue {
        background-color: #0fccef99;
        border: solid 8px #0fccef05;
    }

    .light-blue-hr {
        border-color: #0fccef;
    }

    .light-blue:hover {
        border: solid 8px #0fccef;
    }

    .red {
        background-color: #fa5a4699;
        border: solid 8px #fa5a4605;
    }

    .red-hr {
        border-color: #fa5a46;
    }

    .red:hover {
        border: solid 8px #fa5a46;
    }

    .orange {
        background-color: #f2972999;
        border: solid 8px #f2972905;
    }

    .orange-hr {
        border-color: #f29729;
    }

    .orange:hover {
        border: solid 8px #f29729; 
    }

    .purple {
        background-color: #8751f799;
        border: solid 8px #8751f705;
    }

    .purple-hr {
        border-color: #8751f7;
    }

    .purple:hover {
        border: solid 8px #8751f7;    
    }
    
    .card > hr {
        margin-left: auto;
        margin-right: auto;
    }
    
    .card {
        cursor: pointer;
    }
    
    a {
        color: #007bff;
    }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML-full"></script>
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [["$", "$"], ["\\\\(", "\\\\)"]],
            displayMath: [["$$", "$$"], ["\\[", "\\]"]],
            processEscapes: true
        },
        config: ["MMLorHTML.js"],
        jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
        extensions: ["MathMenu.js", "MathZoom.js"]
    });
</script>
<script>
    $(function() {
        $("div.card").click(function() {
            window.location.href = $(this).attr("href");
        });
    });
</script>
{% endblock %}
{% block main %}
    <h1 class="primary">
        {% if not year %}
        <strong>Current Projects</strong>
        {% else %}
        <strong>Alumni Projects - Graduation Year: {{ year }}</strong>
        {% endif %}
    </h1>
    <div class="row">
        {% for project in projects %}
            <div class="col-xl-4 col-lg-6 col-sm-12">
                <div class="box card card-body text-center
                {% if project.id|divisibleby:'4' %}light-blue
                {% elif project.id|divisibleby:'3' %}red
                {% elif project.id|divisibleby:'2' %}orange
                {% elif project.id|divisibleby:'1' %}purple
                {% endif %}"
                href="{% url 'projects:project_detail' project.id %}"
                >
                    <p><strong>{{ project.title | markdown | safe }}</strong></p>
                    <p>{{ project.author_string }}</p>
                    <hr class=" 
                    {% if project.id|divisibleby:'4' %}light-blue-hr
                    {% elif project.id|divisibleby:'3' %}red-hr
                    {% elif project.id|divisibleby:'2' %}orange-hr
                    {% elif project.id|divisibleby:'1' %}purple-hr
                    {% endif %}">
                    
                    <p>{{ project.description | markdown | safe }}</p>

                    {% if project.has_info_urls %}
                    <hr class=" 
                    {% if project.id|divisibleby:'4' %}light-blue-hr
                    {% elif project.id|divisibleby:'3' %}red-hr
                    {% elif project.id|divisibleby:'2' %}orange-hr
                    {% elif project.id|divisibleby:'1' %}purple-hr
                    {% endif %}">
                    <div class="row urls-row">
                        {% for name, url in project.info_urls.items %}
                            {% if url %}
                            <div class="col">
                                <a href="{{ url }}">
                                    {{ name }}
                                    {% if name == "Video" %}
                                    <span class="fcps-only">(FCPS only)</span>
                                    {% endif %}
                                </a>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    <br><hr><br>
    <div class="alumni-container">
        <h1 class="primary"><strong>Alumni Projects</strong></h1>
        Click on a year to see projects by alumni that graduated in that year.
        <br>
        <ul>
       {% for year in years %}
        <li>
            <a href="{% url 'projects:project_list' year %}">{{ year }}</a>
            <br>
        </li>
       {% endfor %}
    </ul>
    <br>
    </div>
{% endblock %}

qlab/templates/projects/photo.html
{% extends "base_with_head.html" %}

{% load static %}

{% block head %}
    <style>
        #id_title {
            width: 70%;
        }

        .height-holder {
            height: 25vh;
        }
    </style>
{% endblock %}

{% block main %}
    <h1 class="primary"><strong>Add Photo</strong></h1>
    <h5>Project: {{ project }}</h5>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <p>{{ field }}</p>
        {% endfor %}
        <input class="btn q-btn" type="submit" name="button-save" value="Save">
    </form>
    <div class="height-holder"></div>
{% endblock %}

qlab/templates/projects/post.html
{% extends "base_with_head.html" %}

{% load static %}

{% block head %}
    <style>
        #id_title {
            width: 70%;
        }
    </style>
{% endblock %}

{% block main %}
    <h1 class="primary"><strong>{{ action }} Post</strong></h1>
    <h5>Project: {{ project }}</h5>
    <br>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <p>{{ field }}</p>
        {% endfor %}
        <input class="btn q-btn" type="submit" name="button-save" value="Save">
        {% if action == "Edit" %}
            <input class="btn q-btn" type="submit" name="button-delete" value="Delete">
        {% endif %}
    </form>    
{% endblock %}